### PR TITLE
Revert 8a7bf877b3f652a1b7e160469a7e1bbec43e74a0

### PR DESCRIPTION
**Pull request by adriancmiranda**
There is a syntax error at try..catch. This PR only fix it

### CODE REVIEW

**Review by shinnn — CHANGES_REQUESTED** [review]
> There is a syntax error

No. https://travis-ci.com/shinnn/sass-package-importer/builds/80055080

**Comment by shinnn** [comment]
@adriancmiranda Is there any reason you keep this pull request open?

**Comment by shinnn** [comment]
Read https://tc39.github.io/proposal-optional-catch-binding/ to understand why this patch is anything but a “fix”.

**Comment by adriancmiranda** [comment]
Oh, my bad! @shinnn
Thx 4 the explanation! 😄
**edit:** I was trying to use with wrong presets, I think!
- node v8.11.3

**Pull request closed without merging**
